### ISSUE TITLE
qr-write results in cdr: contract violation

### ISSUE THREAD

**Issue by krrrcks** [simmone/racket-simple-qr#5]
When I try to generate a QR code with 
`(qr-write "01_900022_X257EE9MBEASFA4L" "a.png")`
I get a 
```
; cdr: contract violation
;   expected: pair?
;   given: '()
; Context:
;  /home/dbr/.racket/7.3/pkgs/simple-qr/simple-qr/write/qr-write.rkt:266:16 loop
;  /home/dbr/.racket/7.3/pkgs/simple-qr/simple-qr/write/qr-write.rkt:42:0 qr-write18
;  /home/dbr/sw/racket/collects/racket/repl.rkt:11:26
```
As far as I looked into the code I think the problem arises around line 270 in `qr-write.rkt`. There are two `cdr` but for the string aforementioned the list `loop_data_list` is shorter and a `cdr` results in the said bug.

**Comment by simmone** [comment]
Thank you, it's a big bug.

I found the the root cause is not in the simple-qr package itself.

The bug is in my another package: reed-solomon.
simple-qr depend reed-solomon to generate the error code when write and recover error when 
read.

The reason is reed-solomn use euclidean divide the generate error code, but at some cases,
like your "01_900022_X257EE9MBEASFA4L", the divide at the end , not generate enough divideend
(error code). Like this, it needs 16 errorcode, but it generate 15. 
Just add 0's to the head to fill the enough length error code is ok.

Use raco pkg update reed-solomon to fix this bug.
